import { rest } from "msw";
export const handlers = [
  rest.get("http://localhost:5000/data", (req, res, ctx) => {
    return res(
      ctx.status(200),
      ctx.json([
        {
          name: "Bitcoin",
          symbol: "BTC",
          price: 2015273.74,
          image:
            "https://assets.coingecko.com/coins/images/1/large/bitcoin.png?1547033579",
          change: "+6.45%",
          market_capital: "47.19T",
          total_investment: "$637,283,258.87",
          series: [
            { name: "Bitcoin", data: [26, 64, 11, 78, 53, 54] },
            { name: "Total investment", data: [5, 2, 12, 34, 90, 83] },
          ],

          coin_percentage: "+7.40%",
          colors: ["#FFA74F", "#0052FF"],
          backgroundColor: "rgba(247, 147, 26, 0.2)",
          circulating_supply: "1.9M BTC",
          volume_24: "4.12T",
          total_percentage: "-5.8%",
          transactions: [
            {
              bgColor: "#E9F7EC",
              tag: "from Mia Davis",
              value: "+0.0000",
              month: "mar",
              val: "+$0.00",
              status: "purchased",
              date: "29",
              image: "assets/tick.svg",
            },
            {
              month: "jan",
              image: "assets/more_horiz.svg",
              tag: "from Sophia Miller",
              value: "+0.0463 BTC",
              val: "+$2530",
              date: "7",
              status: "purchased",
              bgColor: "#FFF6ED",
            },
            {
              date: "23",
              tag: "from Jason Franklin",
              value: "+0.3095 BTC",
              image: "assets/tick.svg",
              val: "+$1700",
              status: "purchased",
              month: "jul",
              bgColor: "#E9F7EC",
            },
            {
              month: "jun",
              date: "27",
              image: "assets/more_horiz.svg",
              tag: "from Sophia Jones",
              value: "+0.7255 BTC",
              val: "+$1700",
              status: "purchased",
              bgColor: "#FFF6ED",
            },
            {
              tag: "from Olivia Jones",
              value: "+0.0216 BTC",
              val: "+$930",
              date: "31",
              image: "assets/danger.svg",
              status: "purchased",
              bgColor: "#F3E6EB",
              month: "aug",
            },
            {
              month: "feb",
              tag: "from Noah Williams",
              value: "+0.0216 BTC",
              val: "+$1700",
              status: "purchased",
              bgColor: "#FFF6ED",
              date: "14",
              image: "assets/more_horiz.svg",
            },
            {
              date: "24",
              status: "purchased",
              bgColor: "#E9F7EC",
              month: "may",
              image: "assets/tick.svg",
              tag: "from Noah Davis",
              value: "+0.7255 BTC",
              val: "+$4630",
            },
            {
              month: "aug",
              date: "23",
              image: "assets/tick.svg",
              tag: "from Liam Franklin",
              value: "+0.0253 BTC",
              val: "+$840",
              status: "purchased",
              bgColor: "#E9F7EC",
            },
          ],
        },
        {
          name: "Ethereum",
          symbol: "ETH",
          price: 138551.51,
          image:
            "https://assets.coingecko.com/coins/images/279/large/ethereum.png?1595348880",
          change: "-6.57%",
          market_capital: "20.21T",
          total_investment: "$180,830,109.85",
          series: [
            { name: "Ethereum", data: [64, 50, 61, 24, 93, 12] },
            { name: "Total investment", data: [12, 10, 8, 96, 1, 75] },
          ],
          colors: ["#B71A33", "#66A1FF"],
          backgroundColor: "rgba(34, 34, 34, 0.2)",
          circulating_supply: "12.0M ETH",
          volume_24: "0.92T",
          total_percentage: "+0.2%",
          coin_percentage: "-4.20%",
          transactions: [
            {
              month: "feb",
              date: "1",
              image: "assets/more_horiz.svg",
              tag: "from Sophia Franklin",
              value: "+$0.0472 ETH",
              val: "+$4630",
              status: "purchased",
              bgColor: "#FFF6ED",
            },
            {
              date: "18",
              image: "assets/danger.svg",
              tag: "from Noah Brown",
              value: "+0.0463 ETH",
              month: "feb",
              val: "+$2530",
              status: "purchased",
              bgColor: "#F3E6EB",
            },
            {
              status: "purchased",
              bgColor: "#F3E6EB",
              month: "sep",
              date: "4",
              image: "assets/danger.svg",
              tag: "from Olivia Miller",
              value: "+0.0188 ETH",
              val: "+$1880",
            },
            {
              month: "sep",
              date: "1",
              image: "assets/more_horiz.svg",
              tag: "from Sophia Miller",
              value: "+$0.0472 ETH",
              val: "+$1880",
              status: "purchased",
              bgColor: "#FFF6ED",
            },
            {
              status: "purchased",
              bgColor: "#F3E6EB",
              month: "dec",
              date: "5",
              image: "assets/danger.svg",
              tag: "from Ethan Jones",
              val: "+$3520",
              value: "+0.0253 ETH",
            },
            {
              month: "may",
              tag: "from Ethan Williams",
              value: "+0.846 ETH",
              val: "+$3090",
              status: "purchased",
              bgColor: "#FFF6ED",
              date: "4",
              image: "assets/more_horiz.svg",
            },
          ],
        },
      ])
    );
  }),
];
